#!/usr/bin/env bash
# While loop, if 9 say hi
count=1
while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
        echo -e "Hi"
    else
        echo -e "Best School"
    fi
    ((count++))
done