#!/usr/bin/env bash
# Looping through 1-20, using while, and case statements
i=1
while [ $i -le 20 ]; do
  echo "$i"
  case $i in
    4)
      echo -e "bad luck from China"
      ;;
    9)
      echo -e "bad luck from Japan"
      ;;
    17)
      echo -e "bad luck from Italy"
      ;;
  esac
  ((i++))
done