#!/usr/bin/env bash
# Looping through 1-20, using while, and case statements
count=1
while [ $count -le 20 ]
do
    case $count in
        4)
            echo -e "$count/nbad luck from China"
            ;;
        8)
            echo -e "$count/nbad luck from Japan"
            ;;
        17)
            echo -e "$count/nbad luck from Italy"
            ;;
        *)
            echo -e $count
            ;;
    esac
    ((count++))
done